language: node_js
branches:
  only:
    - master
    - develop
node_js:
  - "0.12"
before_install:
  - npm install -g bower grunt-cli karma-cli gulp-cli istanbul coveralls
script:
  - npm test --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

