#!/usr/bin/env bash

# ########################################
#
# Description
# --------
#
# git hook to run a command after `git pull` if package.json was changed
#
# Usage
# --------
# npm install husky --save-dev
# chmod 755 bin/hooks/post-merge
#

# if package.json was changed
if [ $(git diff HEAD@{1} HEAD --name-only | grep 'package.json' -c) -ne 0 ]; then
  npm prune
  # npm install
fi
